# SPDX-FileCopyrightText: The futures-stream-ext authors
# SPDX-License-Identifier: CC0-1.0

# yaml-language-server: $schema=https://json.schemastore.org/github-workflow

# Same as file name
name: audit-dependencies

permissions:
  contents: read

on:
  pull_request:
    # The audit check should only look at crates and their specific versions
    # which are defined through these files. Since the `pull_request` trigger
    # runs on every commit for every open pull request, we want to avoid
    # unnecessary runs.
    paths:
      - "**/Cargo.toml"
  push:
    branches:
      - main
  schedule:
    # Weekly, i.e. on Sunday at 13:37 UTC
    - cron: "37 13 * * 0"
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          persist-credentials: false

      - name: Generate Cargo.lock
        run: cargo generate-lockfile

      - uses: EmbarkStudios/cargo-deny-action@v2
        with:
          # Keep in sync with `Cargo.toml`.
          rust-version: "1.89"
          command: check
          arguments: >-
            --all-features
            --locked
